# ***************************************************************************
# *  Copyright 2022 Joseph Molnar
# *
# *  Licensed under the Apache License, Version 2.0 (the "License");
# *  you may not use this file except in compliance with the License.
# *  You may obtain a copy of the License at
# *
# *      http://www.apache.org/licenses/LICENSE-2.0
# *
# *  Unless required by applicable law or agreed to in writing, software
# *  distributed under the License is distributed on an "AS IS" BASIS,
# *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# *  See the License for the specific language governing permissions and
# *  limitations under the License.
# ***************************************************************************

#  . . .

blueprint:
  name: Sleep Alarm Handler
  description: This blueprint . . .
  domain: automation
  input:
    entity_id:
      name: Entity
      description: The entity id of the Sonos speaker.
      selector:
        entity:
          domain: media_player
          integration: sonos
    awake_start_time:
      name: Awake Start Time
      description: The time for when the stopping of the alarm can start. It will end at the `Sleep Start Time`.
      selector:
        time:
    stop_time_window:
      name: Time Window
      description:
        The number of minutes (up to 6 hours) the script will look forward to find an active alarm to disable
        if music isn't playing. The alarm is re-enabled about 5 minutes after the time it would have gone off.
      default: 60
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: minutes
          mode: slider
    sleep_start_time:
      name: Sleep Start Time
      description: The time for when announcing alarm and playing music can start. It will end at the `Awake Start Time`.
      selector:
        time:
    announce_time_window:
      name: Account Time Window
      description:
        The amount of time, in minutes, to look forward for an alarm to announce. Maximum time is 1439 minutes
        (23 hours and 59 minutes), minimum is 30 minutes and the default is 720 minutes (12 hours).
      default: 720
      selector:
        number:
          min: 30
          max: 1439
          unit_of_measurement: minutes
          mode: slider
    announce_volume_level:
      name: "Alarm Announce Volume Level"
      description: "Float for volume level. Range 0..1. If value isn't given, volume isn't changed."
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
    music_content_ids:
      name: "Music Content IDs"
      description: "The list of music IDs and one will be randomly chosen to play. This could spotify play lists or albums, and radio stations."
      selector:
        object:
    music_volume_level:
      name: "Music Volume Level"
      description: "Float for volume level. Range 0..1. If value isn't given, volume isn't changed."
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
    music_shuffle:
      name: "Shuffle"
      description: "True/false for enabling/disabling shuffle. If value isn't given, shuffle isn't changed."
      default: true
      selector:
        boolean:
    music_repeat:
      name: "Repeat Mode"
      description: "Repeat mode set to off, all, one. If value isn't given, repeat isn't changed."
      default: "all"
      selector:
        select:
          options:
            - "off"
            - "all"
            - "one"
    music_sleep_timer:
      name: Sleep Timer
      description: How long music will play before stopping. Default is 15 minutes. Maximum is 600 (10 hours).
      default: 15
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: minutes
          mode: slider

trigger:
  - platform: state
    entity_id: !input entity_id
    to: "on"
    for: "16:00:00"

action:
  - choose:
      - conditions:
          - condition: time
            after: !input awake_start_time
            before: !input sleep_start_time
        sequence:
          - service: script.stop_sonos_alarm # this needs to be added manually
            data:
              entity_id: !input entity_id
              time_window: !input stop_time_window
    default:
      - service: script.announce_sonos_alarm # this needs to be added manually
        data:
          entity_id: !input entity_id
          time_window: !input announce_time_window
          volume_level: !input announce_volume_level
      - service: script.play_random_media # this needs to be added manually
        data:
          media_content_type: music
          entity_id: !input entity_id
          repeat: !input music_repeat
          volume_level: !input announce_volume_level
          shuffle: !input music_shuffle
          media_content_ids: !input music_content_ids
      - service: sonos.clear_sleep_timer
        data:
          entity_id: !input entity_id
      - service: sonos.set_sleep_timer
        data:
          sleep_time: !input music_sleep_timer # TODO: this needs to be multipled by 60
          entity_id: !input entity_id

mode: single
